#!/usr/bin/env bash
# Syncs front-end/ to B1.
#
# Auto-regenerates front-end/config.js from CFN outputs + APIGW key before
# sync, so a fresh checkout works without manual editing. (config.js is
# gitignored; regen is idempotent.)
set -euo pipefail
: "${AWS_PROFILE:=nyu}"
export AWS_PROFILE
REGION="us-east-1"
ACCOUNT="746140163942"
B1="cc-photos-frontend-${ACCOUNT}"
STACK="cc-photos-stack"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

API_INVOKE_URL=$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiInvokeUrl'].OutputValue" --output text)
API_KEY_ID=$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiKeyId'].OutputValue" --output text)
API_KEY_VALUE=$(aws apigateway get-api-key --api-key "$API_KEY_ID" --include-value \
  --region "$REGION" --query value --output text)
PHOTOS_BUCKET=$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='PhotosBucketName'].OutputValue" --output text)

cat > "${ROOT}/front-end/config.js" <<EOF
// Auto-generated by deploy_frontend.sh. Gitignored.
window.CC_PHOTOS_CONFIG = {
  apiBaseUrl: "${API_INVOKE_URL}",
  apiKey: "${API_KEY_VALUE}",
  photosBucket: "${PHOTOS_BUCKET}",
};
EOF
echo "[config] regenerated config.js for ${API_INVOKE_URL}"

aws s3 sync "${ROOT}/front-end/" "s3://${B1}/" \
  --delete \
  --exclude "config.example.js" \
  --exclude ".DS_Store" \
  --region "$REGION"

# Set proper Content-Type on JS files (S3 sync may default to octet-stream).
aws s3 cp "${ROOT}/front-end/config.js" "s3://${B1}/config.js" \
  --region "$REGION" --content-type "application/javascript"

echo
echo "Frontend live at:"
echo "  http://${B1}.s3-website-${REGION}.amazonaws.com"
